# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2de1beda719a1654432da4a647b9fde00511d12448e02d65249255d524898597d3f80e341c337757bae6cc0088ea163eb7691ae7baa1985ac36661336840bd8e

test:
  secret_key_base: 77eae42e0720cf8e953ac01f2aea4f1f9c8361c10e141c63012673040bd2d01d6fee980d7ff3b3a6ba2abafe4c5ef37ef834567917c758131ce9c742a34138a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
